### ISSUE TITLE
To-do list (DOCUMENTATION PURPOSES)

### ISSUE THREAD

**Issue by mrporsev** [mrporsev/DD2480-Assignment2#8]
Todo

- [ ] CI-server code needs to be uploaded to KTH machine

- [ ] Setup ngrok with CI-server so it is public and can receive payloads

- [ ] Setup web hook to send payload to our public CI-server address

- [ ] Look at the request structure to understand how to filter out values sent from the request

- [ ] Test jGit functionality that has already been created

- [ ] Implement functionality that should happen after request has been processed 
- [ ] 	Build
- [ ] 	Test

- [ ] Send back status of the Build to the REST API of Github

- [ ] Documentation for SEMAT (P6)

- [ ] Create a method to automatically delete the cloned repository/directory
